### ISSUE TITLE
Publish library crate variant

### ISSUE THREAD

**Issue by foresterre** [foresterre/miniview#6]
@kgrzywocz What kind of interface would you like to see, if I were to publish it as a crate (assuming you mean as a library crate; a binary version [exists](https://crates.io/crates/miniview))?

_Originally posted by @foresterre in https://github.com/foresterre/miniview/issues/5#issuecomment-639669860_

**Comment by kgrzywocz** [comment]
Here is my case:
https://github.com/kgrzywocz/league_of_steel/blob/master/testlib/tests/different_resolution.rs
see usage of image::ImageDisplay from
https://github.com/kgrzywocz/league_of_steel/blob/master/testlib/src/image.rs
The whole idea is to display image fullscreen, so during the test my app can get the screenshot and analyze it.

I am no sure how exactly it should work - mainly because of the thread and piston behavior.
From one point of view: It would be great to have all-in-one (I am currently testing running miniview as separate process - almost 2 LoC + sleep;) ). By now it is only problematic as you have to separately run cargo install instead of simple adding miniview in dependency section.
From the second point of view it would be great to be able control (aka know when) the display - so that no "sleep" will be needed (some control pipe maybe?) 

I also have some strange problem on Win10 with Dx9 - capturing the screen leaves whole white screen, but that is kind of Dx9/Piston problem (I got the same using my current code)

**Comment by kgrzywocz** [comment]
To conclude with some PoC:
```
let view= miniview::open_from_path("image.png", [fullscreen]); //flags or some builder pattern like windows options 
view.wait_for_image_on_screen(); // optional?
view.stop() // or just drop?
```

**Comment by foresterre** [comment]
Thanks for your explanation! I don't really have time to look at it today, but hope to look at it in the very soon (i.e. I haven't forgotten about it 😄). I've so far prototyped some builder pattern for the interface which in my humble opinion looks more pleasing than flags, but I'll give flags also a try (perhaps it does work out better after all!).

**Comment by kgrzywocz** [comment]
Builder usually works better over time ;)
By now I am using my own changed build - so yo don't have to rush ;)

Anyways if you have any ideas what may be wrong with taking screenshots on Win 10 let me know - I am a bit stuck and I will probably need to create an issue on piston

**Comment by kgrzywocz** [comment]
I am not sure where I have to place my comments, so I will do it here: )
I got draft of something like that:
```rust
        let config = miniview::config::ConfigBuilder::from_path(file)
            .set_fullscreen(true)
            .close_window_when(Some(Box::new(|| res.is_active())))
            .build();
        miniview::show(&config);
```
The main idea looks good ;) However there are some problems:
1. ```pub use config::ConfigBuilder``` ?
2. ```show()``` blocks thread - not a big deal
3.  ```.close_window_when(Some(Box::new(|| res.is_active())))```

The last thing is the most problematic, because it is far to complicated to use:
- you cannot use it 'in-place' aka `res` cannot be ```self```, because it has to be moved, so it will require some proxy object
 - it cannot be used multithreded which is the main thing here. You probably want to show image and wait for user or do something else meanwhile (my case)
- this ```Some``` shows a bit of internals - this is cosmetics, so nothing to worry ;)

Suggested solutions:
If you decide to provide separate thread, then ```show()``` could return some proxy object with for example ```stop``` method. The other option would be some "proxy object" using for example ```std::sync::mpsc``` :
```rust
let controls=config.create_controls(); // internally creates mpsc::channel(); saving internally rx returning object with tx
...
miniview::show(&config); // in main loop instead of "should_exit()" calling rx.try_recv() and checking if it should exit
...
//not related stuff - main difference between my use and 'main.rs'
...
controls.stop(); //calls tx.send()
```

```controls```  may be also result of show ;)

I am no sure if I made my self clear - don't hesitate to ask about details. I can also fork and write some prove of concept - always easier to talk about code then idea ;)

Anyways: thank you very much for your effort - I think we are close ;)

**Comment by kgrzywocz** [comment]
About the screenshot issue [piston ticket](https://github.com/PistonDevelopers/piston/issues/1349)
I think this is may be more windows issue - it works on windows 18xx, but not on 1909. I don't have SDL installed...

**Comment by foresterre** [comment]
Thanks for the excellent feedback, much appreciated, it's great to learn new things!
I've given it another shot based on your feedback.

Instead of the previous

```rust
        let config = miniview::config::ConfigBuilder::from_path(file)
            .set_fullscreen(true)
            .close_window_when(Some(Box::new(|| res.is_active())))
            .build();
        miniview::show(&config);
```


now you would do:

```
  use miniview::{ConfigBuilder, MiniView};

    let config =
        ConfigBuilder::from_path(file)
            .set_fullscreen(true)
            .build();

    let controls = MiniView::show(config).expect("unable to create miniview");

    // do some unrelated other work!
    std::thread::sleep(Duration::from_millis(1000));

    let closed = controls.close();
    assert!(closed.is_ok());
```

**Comment by kgrzywocz** [comment]
It works as it should - thank you;)\
Here is my real usage:
```rust
use miniview;

pub struct ImageWindow {
    controls: miniview::MiniView,
}

impl ImageWindow {
    pub fn new(width: u32, height: u32, file: &str) -> Self {
        super::resolution::set_resolution(width, height);

        let config = miniview::ConfigBuilder::from_path(file)
            .set_fullscreen(true)
            .build();
        let controls = miniview::MiniView::show(config).unwrap();

        Self { controls }
    }
    pub fn stop(self) {
        self.controls.close().unwrap();
    }
}
```

I don't think reusable ```close``` is is need here - it will probably complicate things (what should happened after it is called?), but if you really want it: You can put it into for example ```Option``` - take owner ship and set option to ```None```. That will allow you to have ```&self``` (reference to ```Option``` not the thread it self). Note that this way rust force you to write this "after close" code ;)

I see that you created ```MiniView``` object looks fine ;) Now "show"is kind of "new" - I am still thinking which name is better. "new" is more in accordance with the convention, but "show" is also ok;)

Is there something more that need to be done internally? When can I expect new version on [crates.io](https://crates.io/)? :)

Once again thank you;)

**Comment by foresterre** [comment]
Amazing, thanks for the feedback! I learned a lot from this 😄 
I will merge the PR and publish a new version on crates.io after that :).
